name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  watch:
    types: [started]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run code
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ruby profile_updater.rb
